import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,stat,readFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright-core';
import {browserPath} from '../scripts/pdf.mjs';
import {createResumeServer} from '../scripts/preview.mjs';

test('home creates from public presets and supports cancel, restore and permanent deletion on desktop and mobile',async t=>{
  let executablePath;
  try{executablePath=await browserPath();}catch{t.skip('Install Chrome / Edge to run the browser integration test');return;}
  const source=fileURLToPath(new URL('../',import.meta.url));
  const root=await mkdtemp(path.join(os.tmpdir(),'zhijian-home-'));
  for(const name of ['app','assets/brand','assets/fonts','assets/photo-placeholder.svg','assets/school-placeholder.svg','home.html','editor.html','styles.css'])
    await cp(path.join(source,name),path.join(root,name),{recursive:true});
  const server=await createResumeServer({projectRoot:root});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({executablePath,headless:true});
  t.after(async()=>{await browser.close();await new Promise(resolve=>server.close(resolve));});
  const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),errors=[];
  page.setDefaultTimeout(12000);
  page.on('pageerror',error=>errors.push(error.message));
  const base=`http://127.0.0.1:${server.address().port}`;
  const get=async url=>(await fetch(base+url)).json();
  const ready=async()=>page.locator('#library-message').waitFor({state:'hidden'});
  const studio=async()=>{await page.goto(base+'/#studio',{waitUntil:'load'});await ready();};
  const count=async(live,trash)=>{
    await page.waitForFunction(([live,trash])=>document.querySelectorAll('.resume-card').length===live&&document.querySelector('#trash-count').textContent===String(trash),[live,trash]);
  };
  await studio();await count(0,0);
  await page.locator('#new-resume').click();
  assert.deepEqual(await page.locator('#resume-source option').evaluateAll(options=>options.map(o=>o.value)),['preset:blank','preset:demo']);
  await page.locator('#resume-name').fill('演示简历 · 科研方向');
  await page.locator('#resume-description').fill('测试数据，用于验证模板、恢复和删除。');
  await page.locator('#resume-source').selectOption('preset:demo');
  assert.match(await page.locator('#source-hint').textContent(),/虚构/);
  await page.locator('#save-resume').click();await page.waitForURL('**/editor.html?id=*');
  await page.locator('[data-field="profile.name"]').waitFor();
  assert.match(await page.locator('[data-field="profile.name"]').inputValue(),/演示/);
  const demoId=new URL(page.url()).searchParams.get('id');
  const original=await get('/api/resumes/'+demoId+'/data');

  await studio();await count(1,0);
  await page.locator('#new-resume').click();
  const blankName='<img src=x onerror=alert(1)> 空白简历';
  await page.locator('#resume-name').fill(blankName);
  await page.locator('#save-resume').click();await page.waitForURL('**/editor.html?id=*');
  await page.locator('[data-field="profile.name"]').waitFor();
  assert.equal(await page.locator('[data-field="profile.name"]').inputValue(),'');
  const blankId=new URL(page.url()).searchParams.get('id');
  const blankPath=path.join(root,'data','resumes',blankId,'resume.json'),blankRaw=await readFile(blankPath,'utf8');

  await studio();await count(2,0);
  const remove=page.locator('[data-delete="'+demoId+'"]');
  await remove.click();
  assert.equal(await page.locator('#cancel-delete').evaluate(el=>el===document.activeElement),true);
  await page.keyboard.press('Enter');assert.equal(await page.locator('#delete-dialog').isVisible(),false);
  await remove.click();await page.keyboard.press('Escape');await count(2,0);
  await remove.click();
  await page.route('**/api/resumes/'+demoId,route=>route.abort());
  await page.locator('#confirm-delete').click();await page.locator('#delete-error').waitFor();
  assert.equal((await get('/api/resumes')).resumes.length,2);
  await page.unroute('**/api/resumes/'+demoId);
  await page.locator('#confirm-delete').click();await page.locator('#delete-dialog').waitFor({state:'hidden'});
  await count(1,1);
  await page.locator('#show-trash').click();await ready();
  assert.equal(await page.locator('#resume-grid').isVisible(),false);
  assert.equal(await page.locator('.trash-copy h3').textContent(),original.document.name);
  await page.screenshot({path:path.join(root,'trash-desktop.png'),fullPage:true});
  await page.locator('[data-restore="'+demoId+'"]').click();await count(2,0);
  await page.locator('#trash-empty').waitFor();
  assert.deepEqual((await get('/api/resumes/'+demoId+'/data')).data,original.data);
  await page.locator('#show-library').click();
  await page.locator('[data-delete="'+demoId+'"]').click();
  await page.locator('#confirm-delete').click();await page.locator('#delete-dialog').waitFor({state:'hidden'});await count(1,1);

  await page.locator('[data-delete="'+blankId+'"]').click();
  assert.equal(await page.locator('#delete-document-name').textContent(),blankName);
  assert.equal(await page.locator('#delete-document-name img').count(),0);
  await page.locator('#cancel-delete').click();
  await page.locator('#show-trash').click();await ready();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(root,'trash-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  const purge=page.locator('[data-purge="'+demoId+'"]');
  await purge.click();
  assert.match(await page.locator('#delete-title').textContent(),/彻底删除/);
  assert.match(await page.locator('#delete-description').textContent(),/无法撤销/);
  await page.screenshot({path:path.join(root,'purge-mobile.png'),fullPage:true});
  await page.keyboard.press('Escape');await count(1,1);
  await purge.click();await page.locator('#confirm-delete').click();
  await page.locator('#delete-dialog').waitFor({state:'hidden'});await count(1,0);
  await assert.rejects(stat(path.join(root,'data','deleted',demoId)),error=>error.code==='ENOENT');
  assert.equal(await readFile(blankPath,'utf8'),blankRaw);
  await page.reload({waitUntil:'load'});await ready();await count(1,0);
  await page.goto(base+'/editor.html?id='+demoId,{waitUntil:'load'});
  await page.locator('#notice').filter({hasText:'这份简历已被删除或不存在，请返回工作台。'}).waitFor();
  assert.deepEqual(errors,[]);
  t.diagnostic('Mock UI screenshots: '+root);
});
